// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnvRRBLqAtLyKWVCAfZRWwmtj2fh_Qr3U',
    appId: '1:778294035953:web:1b1aeb4f834899d17db050',
    messagingSenderId: '778294035953',
    projectId: 'todos-6e637',
    authDomain: 'todos-6e637.firebaseapp.com',
    storageBucket: 'todos-6e637.firebasestorage.app',
    measurementId: 'G-ZJX90V2J1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx2oB4gnycXlru5XaEuaVnH1bWfUelFmE',
    appId: '1:778294035953:android:fc618f07d56b5e697db050',
    messagingSenderId: '778294035953',
    projectId: 'todos-6e637',
    storageBucket: 'todos-6e637.firebasestorage.app',
  );
}
